<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.6.5 on win32)" generated="20200830 22:03:27.568" rpa="false">
<suite id="s1" name="Get Request" source="F:\RobotScripts\APIAutomation\Tests\Get_Request.robot">
<test id="s1-t1" name="Get Weather Information of City">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>mySession</arg>
<arg>${base_url}</arg>
</arguments>
<msg timestamp="20200830 22:03:27.745" level="INFO">Creating Session using : alias=mySession, url=http://restapi.demoqa.com, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20200830 22:03:27.744" endtime="20200830 22:03:27.745"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>mySession</arg>
<arg>/utilities/weather/city/${city}</arg>
</arguments>
<assign>
<var>${response}</var>
</assign>
<msg timestamp="20200830 22:03:30.803" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD1609BDD8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /utilities/weather/city/Hyderabad</msg>
<msg timestamp="20200830 22:03:31.008" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD1608DEB8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /utilities/weather/city/Hyderabad</msg>
<msg timestamp="20200830 22:03:31.417" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD176E22E8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /utilities/weather/city/Hyderabad</msg>
<msg timestamp="20200830 22:03:31.568" level="FAIL">ConnectionError: HTTPConnectionPool(host='restapi.demoqa.com', port=80): Max retries exceeded with url: /utilities/weather/city/Hyderabad (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD176E2588&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))</msg>
<status status="FAIL" starttime="20200830 22:03:27.747" endtime="20200830 22:03:31.568"></status>
</kw>
<status status="FAIL" starttime="20200830 22:03:27.743" endtime="20200830 22:03:31.577" critical="yes">ConnectionError: HTTPConnectionPool(host='restapi.demoqa.com', port=80): Max retries exceeded with url: /utilities/weather/city/Hyderabad (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD176E2588&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))</status>
</test>
<status status="FAIL" starttime="20200830 22:03:27.570" endtime="20200830 22:03:31.579"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Get Request">Get Request</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200830 22:03:30.803" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD1609BDD8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /utilities/weather/city/Hyderabad</msg>
<msg timestamp="20200830 22:03:31.008" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD1608DEB8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /utilities/weather/city/Hyderabad</msg>
<msg timestamp="20200830 22:03:31.417" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001DD176E22E8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /utilities/weather/city/Hyderabad</msg>
</errors>
</robot>
